all-contributors/app

serverless.yml
src/processIssueComment.js
src/utils/isMessageForBot.js
src/utils/parse-comment/index.js
test/setup.js
test/utils/isMessageForBot.test.js
test/utils/parse-comment/index.test.js

Fixes cases where usernames not correctly parsed.
Also addressed issue where bot name was @@botname in some cases

fix: in some cases usernames are not correctly parsed

---

src/utils/parse-comment/index.js
test/utils/parse-comment/index.test.js

feat: support adding people with mentions

---

src/processIssueComment.js

This showed up in sentry: https://sentry.io/all-contributors/github-bot/issues/845638720/events/42773873695/

fix: commentReply is not a function

---

src/Repository/index.js
src/utils/getUserDetails.js

Due to deprecation warnings, I changed the `code` attribute to `status` to fix #54.
_Note_: the `master` branch (up to e241b5d81352a1645cf9f2b8ec1ff90989b9a455) seems to fail when locally running `yarn test` namely with this error: `TypeError: initBadge is not a function`.

fix: changed `error.code` to `error.status` (#54)

---

app.yml

Hiya! Super cool app and even cooler that you built it with Probot! I was just peaking at the code and noticed this very minor nit. (Feel free to ignore!)
Right now GitHub App names are namespaced in a way in which they must be entirely unique from all other app, user, or org names. Therefore, filling in this name value results in an error. This will always happen due to the name defaulting from the package.json, but it just means this is irrelevant 🤷‍♀️

Remove name field from app.yml

---

serverless.yml
src/serverless-health-check.js

https://github.com/probot/probot.github.io/pull/282 needs a ping endpoint

feat: add health check/ping endpoint

---

src/tasks/processIssueComment/ContentFiles/index.js

Related sentry error: https://sentry.io/organizations/all-contributors/issues/914046607/?project=1366866&referrer=slack&statsPeriod=14d

fix: sentry type error AllContributorBotError is not a constructor

---

serverless.yml

This is another mitigation against https://github.com/all-contributors/all-contributors-bot/issues/167
Keeping the lambda warm, along with memory cache (https://github.com/all-contributors/all-contributors-bot/pull/133) during the time we expect probot to sync should help mitigate against this.
See also https://github.com/probot/probot/issues/380

infra: keep stats lambda warm when probot sync happens

---

package.json
src/serverless-webhook.js
src/tasks/stats/serverless-stats-worker.js
yarn.lock

closes #217 
I’m not sure if disabling the new `require-atomic-updates` rule is the best fix here, there might be a more elegant solution that would require more refactoring. It looks like a false positive to me here

Greenkeeper/eslint 6.0.1

---

src/tasks/processIssueComment/utils/parse-comment/index.js

I found this small typo when reading through the source code, so I thought I'd fix it 👍

chore: fix typo in parse-comment

---

contributing/bot-architecture.md
src/tasks/processIssueComment/utils/parse-comment/index.js

Hi,
This tiny PR will fix : 
- 1 typo in `contributing/bot-architecture.md`
- 1 typo in `src/tasks/processIssueComment/utils/parse-comment/index.js`
Best! :robot:

docs: fix typos

---

.github/workflows/stats.yml

See https://github.com/wip/app/actions?query=workflow%3AStats for comparison.
FYI the app has currently 3334 installations.

ci: run daily stats action

---

.github/workflows/stats.yml

I use the same setup for the WIP app:
https://github.com/wip/app/blob/bd19096682b84a1adea0ca426e7c6bec1fa41ba1/.github/workflows/stats.yml\#L19-L29
This will permit us to add the number of total installations/repositories to a dashboard such as the one form WIP:
https://wip.vercel.app
(for some reason the dashboard is not working right now, here is a screenshot of what it looks like, I want to create something similar for the All Contributors app)

ci(stats): log data to logflare

---

contributing/bot-architecture.md
contributing/run-bot-locally.md
lib/get-user-details.js
lib/to-safe-git-reference-name.js
privacy-policy.md
test/unit/parse-comment.test.js

This PR corrects misspellings identified by the [check-spelling action](https://github.com/marketplace/actions/check-spelling).
The misspellings have been reported at https://github.com/jsoref/all-contributors-app/commit/d0a260308e5be2d7b5d5993a28d63e4b468a8372#commitcomment-46057781
The action reports that the changes in this PR would make it happy: https://github.com/jsoref/all-contributors-app/commit/deb25b05844f9eeb0617fc790bbf2b921ee5d02f
Note: this PR does not include the action. If you're interested in running a spell check on every PR and push, that can be offered separately.

docs: spelling fixes

---

package-lock.json
package.json

To make sure dependencies are up-to-date and will ensure that the app uses the latest version of the CLI (which should help in mitigating issues that were normally fixed).
Re #354

fix(deps): bump dependency versions

---

lib/modules/repository.js

**What**: 
- Found unnecessary error handling in `app/lib/modules/repository.js`
**Why**:
- To achieve 100% test coverage.
**How**:
- Remove unnecessary error handling in `app/lib/modules/repository.js` (already handled by this line) 
https://github.com/all-contributors/app/blob/e33b4823825d554847dfd6285969cdb1d664edf5/lib/modules/repository.js#L222
**Checklist**:

chore: remove unnecessary error handling

---

lib/add-contributor.js
test/integration/__snapshots__/issue_comment.test.js.snap

**What**:
- Commit message does not include contribution types anymore.
**Why**:
-  Include contribution types in the commit message
**How**:
- Update code regarding commit message
**Checklist**:

fix: include contribution types in commit message

---

lib/add-contributor.js
lib/modules/helpers.js
test/unit/helpers.test.js

**What**:
- Fixes https://github.com/all-contributors/all-contributors/issues/645
**Why**:
- Found bug
**How**:
- Update code and write tests
**Checklist**:

fix: resolve commit message issue

---

lib/parse-comment.js

- We are adding research and promotion keywords to parse-comment.js 
- for Issue #399
**What**: Adding new keywords to parse-comment.js
**Checklist**:

fix: define `research` and `promotion` contribution types

---

lib/parse-comment.js

Fixes the order of keys in the mapping. It's now again alphabetical as it should be 
**Checklist**:

chore: reorder of contribution type mappings

---

lib/parse-comment.js

**What**: Add support for UK English spelling of `event organising` (US English only supported right now: `event organizing`).
**Why**: @aleesteele and I noticed some issues and confusion in trying to add a contributor which was solely the result of only the US english spelling being recognized. See also [the original comments where this took place](https://github.com/alan-turing-institute/the-turing-way/issues/2982?notification_referrer_id=NT_kwDOACz1KLI1NzM3OTAzNzA2OjI5NDYzNDQ#issuecomment-1494387264).
**How**: By adding a multiword mapping for the UK English
**Checklist**:
Thanks for this fantastic project! I am opening this PR as a suggestion, and appreciate any time you give …

fix: support for "event organising" (UK English)

---

lib/process-issue-comment.js
test/fixtures/issue_comment.created.json
test/integration/__snapshots__/issue_comment.test.js.snap

**What**: Fixes #468.
**Why**: Currently, the bot comments _"I couldn't determine ..."_ as soon as a potential contributor is found to not have any contributions. But if there are multiple potential contributors, that comment shouldn't happen.
**How**: With these changes, the comment is only added after all potential contributors are checked for sending a PR.
**Checklist**:
- ~[ ] Added myself to contributors table.~

fix: only comment about no contributions after checking all contributors
