all-contributors/app

.gitignore, CONTRIBUTING.md, serverless.yml, src/handler.js, src/serverless-lambda.js
This forks https://github.com/probot/serverless-lambda
Can un-fork once https://github.com/probot/serverless-lambda/pull/13 is merged
=> feat: add sentry support

src/utils/parse-comment/index.js, test/utils/parse-comment/index.test.js
=> Support full words (like infrastructure) instead of just keys like infra

README.md
=> docs: document requirements for initial setup

src/Repository/index.js, src/processIssueComment.js, test/Repository/index.test.js
=> feat: create pull request on the default branch

package.json, src/processIssueComment.js, src/utils/git/getSafeRef.js, test/utils/git/getSafeRef.test.js, yarn.lock
=> fix: usernames can have brackets

serverless.yml
=> feat: add cache to api-gateway in-front of stats endpoint

package.json, serverless.yml, yarn.lock
=> feat: cache stats api

src/OptionsConfig/index.js, test/OptionsConfig/index.test.js
=> fix: ensure profile URLs have protocol

.circleci/config.yml, .circleci/deploy.sh, CONTRIBUTING.md, serverless.yml
=> infra: add sandbox

README.md, app.yml, src/tasks/processIssueComment/probot-processIssueComment.js
For https://github.com/all-contributors/all-contributors/issues/150
=> feat: use all contributors.org

src/tasks/processIssueComment/Repository/index.js
closes #142 
github api doc: https://developer.github.com/v3/pulls/#list-pull-requests
=> fix: links to incorrect pull request when updating

src/serverless-webhook.js, src/tasks/trackInstall/index.js, test/serverless-webhook.test.js
=> infra(Analytics): track app installs and uninstalls

src/tasks/processIssueComment/probot-processIssueComment.js, src/tasks/trackInstall/index.js, src/utils/Analytics.js, test/utils/Analytics.test.js, test/utils/__snapshots__/Analytics.test.js.snap
Reverts all-contributors/all-contributors-bot#162
This actually works as a login user string too, rolling back
=> Revert "fix(Analytics): log user correctly"

package.json, test/tasks/processIssueComment/probot-app-e2e.test.js, yarn.lock
In favour of https://github.com/all-contributors/all-contributors-bot/pull/158
=> infra: probot 9

CONTRIBUTING.md
With some code in https://github.com/all-contributors/all-contributors-bot/commit/abf0c7a75af7a039677cb1e8d261dee8b5ebf34f, Closes #11
=> docs(Monitoring): add Thundra monitor

src/tasks/processIssueComment/ContentFiles/index.js
=> fix: raise maximum content file limit to 15

src/serverless-webhook.js, test/serverless-webhook.test.js
=> fix: allow bot to respond to other bots too

src/serverless-webhook.js, test/serverless-webhook.test.js
=> test: Implement user/bot response tests

src/tasks/processIssueComment/utils/parse-comment/index.js
Related to https://github.com/all-contributors/all-contributors/issues/320
=> feat: Add a11y contribution type

.gitignore, src/serverless-webhook.js, src/tasks/processIssueComment/OptionsConfig/index.js, src/tasks/processIssueComment/Repository/index.js, test/serverless-webhook.test.js, test/tasks/processIssueComment/__snapshots__/probot-app-e2e.test.js.snap
Fixes #266 and #270 introduced by  #249
=> fix: stop spamming users when crashing, fix .length of undefined when adding contribution

package.json, yarn.lock
=> fix: ensure badge replacement does not break markdown

src/tasks/processIssueComment/probot-processIssueComment.js, test/tasks/processIssueComment/__snapshots__/probot-app-e2e.test.js.snap
Moving to try and make it so my GitHub notifications are useful again
Sorry @someone 🙈
=> fix: stop @jakebolam getting 100+ github notifications a day

README.md
=> docs: standardization of buttons

package.json, src/tasks/processIssueComment/utils/parse-comment/index.js, yarn.lock
Implements the "Data" category from all-contributors/all-contributors#336
and all-contributors/all-contributors-cli#231.
Cfr. all-contributors/all-contributors#334.
Using #166 as model.
=> feat(processIssueComment): added 'data' contributors

src/tasks/processIssueComment/utils/parse-comment/index.js
To keep the bot in sync with https://github.com/all-contributors/all-contributors-cli/pull/261 and https://github.com/all-contributors/all-contributors/pull/371
=> feat(parse-comment): add missing `audio` words

public/index.html
This pull requests embeds the report from https://datastudio.google.com/u/0/reporting/2859cd15-ef97-43b0-a6be-678dc58157f4/page/ecMvB at https://all-contributors-app.vercel.app/. Preview https://app-git-stats-dashboard.all-contributors-app.vercel.app/
=> feat: data dashboard

contributing/run-bot-locally.md, package-lock.json, package.json
Finally had a chance to play around a bit more.
Updating the Docs to address the problems I mentioned in #349 - this should close #349
=> docs(contributing): update "run bot locally" for latest version

lib/add-contributor.js, test/integration/__snapshots__/issue_comment.test.js.snap
1.  Add contribution types in the title.
2.  Remove the "s" in "Adds" in the body. An alternative is "This PR adds", but IMO "Adds" doesn't make sense.
=> feat: improve the title and body of the pull request

CONTRIBUTING.md
**What**:
- Remove all Slack references since those are obsolete and irrelevant now.
**Why**: 
- Those references since are obsolete and irrelevant now.
**How**:
- Remove them all in the codebase.
**Checklist**:
=> chore: remove all Slack references

.github/workflows/test.yml, README.md, package-lock.json, package.json
**What**: 
- Fix Codecov
**Why**:
- Fix Codecov
**How**:
- Fix Codecov
**Checklist**:
=> chore: fix codecov

lib/get-user-details.js, lib/modules/helpers.js, test/unit/helpers.test.js
**What**:
- Fixes https://github.com/all-contributors/app/issues/420
**Why**:
- Some profile link are invalid due to missing protocol
**How**:
- Check and correct links by adding protocol
**Checklist**:
=> fix: resolve invalid link for `profile`

lib/get-user-details.js, lib/modules/helpers.js, test/unit/helpers.test.js
**What**:
- add stricter checks in link for `profile` 
CC @Roshanjossey
**Why**:
- due to lack of GH parsing blog links
**How**:
- update code for profile link
**Checklist**:
=> fix: add stricter checks in link for `profile`

lib/modules/repository.js, lib/setup-repository.js, test/unit/setup-repository.test.js
**What**:
- Resolve PR branch issues
- Fixes https://github.com/all-contributors/app/issues/336.
- Recreate https://github.com/all-contributors/app/pull/338. Special thanks to @hertzg.
**Why**:
- resolve PR branch issues
**How**:
- Refactor code
- Add tests
**Checklist**:
=> fix: resolve PR branch issues

lib/parse-comment.js
**What**:
- rename `videoes` to `videos`
**Why**:
- fix typo
**How**:
**Checklist**:
=> fix: rename `videoes` to `videos`

lib/add-contributor.js, lib/modules/helpers.js, test/integration/__snapshots__/issue_comment.test.js.snap, test/unit/helpers.test.js
**What**:
- Fixes https://github.com/all-contributors/app/issues/417.
**Why**:
**How**:
**Checklist**:
=> feat: add `skip ci` flag in PR description

api/github/webhooks.js
This resolves a problem with logflare
=> fix: use vanilla `pino` instance for logging

lib/parse-comment.js, test/unit/parse-comment.test.js
**What**:
Fixes a bug where a username with multiple dashes is not formatted correctly and the username is not found 
**Why**:
https://github.com/analogjs/analog/pull/362#issuecomment-1529114039
**How**:
Replaces all occurrences of a dash in the username. Removes all occurrences of the replacement characters
**Checklist**:
=> fix: support usernames with multiple dashes

README.md
**What**:
Update shields.io badge for all-contributors ; see https://allcontributors.org/docs/en/bot/faq#all-contributors-badge-count-does-not-update
**Why**:
The current badge shows the incorrect number of contributors to this project.
**How**:
Manually inspected via GitHub UI rendering the changed `README.md` file.
**Checklist**:
=> docs: Update shields.io badge for all-contributors
